In [9]:
from pathlib import Path
import numpy as np
import pandas as pd
from PIL import Image

In [7]:
ROOT = (Path.cwd().parent / "archive").resolve()
CLASSES = ["scissors", "rock", "paper"]

In [15]:
records = []

for label in CLASSES:
    """
    budowa dataframe z informacjami o obrazach
    """
    for path in (ROOT / label).iterdir():
        if path.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
            continue

        with Image.open(path) as img:
            records.append({
                "path": str(path.relative_to(ROOT.parent)),
                "label": label,
                "width": img.width,
                "height": img.height,
                "format": img.format,
            })


df = pd.DataFrame(records)

In [17]:
df.head()

                                    path     label  width  height format
0  archive\scissors\0657zSfiTYzP2jrl.png  scissors    300     200    PNG
1  archive\scissors\0CSaM2vL2cWX6Cay.png  scissors    300     200    PNG
2  archive\scissors\0ePX1wuCc3et7leL.png  scissors    300     200    PNG
3  archive\scissors\0Flw60Z2MAWWKn6S.png  scissors    300     200    PNG
4  archive\scissors\0Ug54ifXRqqlZS2Z.png  scissors    300     200    PNG

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2188 entries, 0 to 2187
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   path    2188 non-null   str
 1   label   2188 non-null   str
 2   width   2188 non-null   int64
 3   height  2188 non-null   int64
 4   format  2188 non-null   str
dtypes: int64(2), str(3)
memory usage: 178.3 KB

In [22]:
df.describe()

        width  height
count  2188.0  2188.0
mean    300.0   200.0
std       0.0     0.0
min     300.0   200.0
25%     300.0   200.0
50%     300.0   200.0
75%     300.0   200.0
max     300.0   200.0